# Generated by Django 4.2.7 on 2024-05-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedJobs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empemailaddress', models.CharField(max_length=100)),
                ('jobtitle', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('address', models.CharField(max_length=200)),
                ('contactno', models.CharField(max_length=15)),
                ('emailaddress', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=30)),
                ('keyskills', models.CharField(max_length=200)),
                ('applieddate', models.CharField(max_length=30)),
            ],
        ),
    ]
