# Generated by Django 4.2.7 on 2024-04-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employeer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firmname', models.CharField(max_length=100)),
                ('firmwork', models.CharField(max_length=10)),
                ('firmaddress', models.EmailField(max_length=254, unique=True)),
                ('cpname', models.CharField(max_length=50)),
                ('cpcontactno', models.BigIntegerField()),
                ('cpemailaddress', models.EmailField(max_length=254, unique=True)),
                ('aadharno', models.CharField(max_length=14)),
                ('panno', models.CharField(max_length=10)),
                ('gstno', models.CharField(max_length=15)),
                ('regdate', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=6)),
                ('address', models.CharField(max_length=255)),
                ('contactno', models.BigIntegerField()),
                ('emailid', models.EmailField(max_length=254)),
                ('enquirytext', models.CharField(max_length=255)),
                ('posteddate', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Jobseeker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.IntegerField()),
                ('address', models.TextField()),
                ('qualification', models.CharField(max_length=256)),
                ('dob', models.CharField(max_length=256)),
                ('experience', models.PositiveSmallIntegerField()),
                ('keyskills', models.CharField(max_length=256)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Valid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('usertype', models.CharField(max_length=10)),
            ],
        ),
    ]
