# Generated by Django 4.2.7 on 2024-04-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firmname', models.CharField(max_length=100)),
                ('jobtitle', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=50)),
                ('jobdesc', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('posteddate', models.CharField(max_length=30)),
                ('emailaddress', models.CharField(max_length=60, unique=True)),
            ],
        ),
    ]
