# Generated by Django 4.2.7 on 2024-05-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobproviderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='emailaddress',
            field=models.CharField(max_length=60),
        ),
    ]
